<a href="https://colab.research.google.com/github/lohi629/Data-Analysis/blob/main/numpy_exam1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
import pandas as pd
arr=[10,20,30,40,40]
for i in range(len(arr)):
  arr[i]=arr[i]+12
  arr[i]=arr[i]-2
print(arr)


[20, 30, 40, 50, 50]


In [14]:
a=np.array([[1,2],[3,4]])
b=np.array([[0,0],[0,0]])
print(a+b)
print(a-b)
print(a*b)


[[1 2]
 [3 4]]
[[1 2]
 [3 4]]
[[0 0]
 [0 0]]


In [17]:
arr1=np.array([1,2,3,4])
arr2=np.array([[2,4],[6,8]])
arr3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr1,arr2,arr3,end="\n")
print(arr1.ndim,arr2.ndim,arr3.ndim)

[1 2 3 4] [[2 4]
 [6 8]] [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
1 2 3


In [18]:
mat=np.eye(5,2)
mat

array([[1., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [20]:
arr1.reshape(4,1)
np.ravel(arr2)

array([2, 4, 6, 8])

In [25]:
arr5=np.array([[1,2],[3,4]])
arr6=np.array([[10,11],[12,13]])
print(np.vstack([arr5,arr6]))
np.hstack([arr5,arr6])

[[ 1  2]
 [ 3  4]
 [10 11]
 [12 13]]


array([[ 1,  2, 10, 11],
       [ 3,  4, 12, 13]])

In [26]:
print(arr3[0,1,1])

5


In [27]:
print(arr3[1:4])

[[[ 7  8  9]
  [10 11 12]]]


In [31]:
print(np.min(arr1))
print(np.max(arr1))
print(np.mean(arr1))
print(np.median(arr1))
print(np.std(arr1))

1
4
2.5
2.5
1.118033988749895


In [32]:
arr7=np.array([[1,2],[3,4]])
arr8=np.array([[2,4],[3,8]])
print(np.dot(arr7,arr8))
print(arr7*arr8)


[[ 8 20]
 [18 44]]
[[ 2  8]
 [ 9 32]]


In [33]:
np.linalg.eig(arr7)

(array([-0.37228132,  5.37228132]), array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

In [34]:
np. linalg. inv(arr7) 

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [35]:
np.linalg.det(arr7)

-2.0000000000000004

In [36]:
np.linalg.matrix_rank(arr7)

2