In [31]:
import numpy as np
import pandas as pd
arr=np.array([[1,2,3],[2,5,8]])
print(arr)


[[1 2 3]
 [2 5 8]]


In [17]:
#transpose
print("transpose:",arr.T)
#flipLR
print("fLR:",np.fliplr(arr))
#flipUD
print("updown:",np.flipud(arr))
#rotate 90
print("rotate:",np.rot90(arr,3))

transpose: [[1 2]
 [2 5]
 [3 8]]
fLR: [[3 2 1]
 [8 5 2]]
updown: [[2 5 8]
 [1 2 3]]
rotate: [[2 1]
 [5 2]
 [8 3]]


In [39]:
#stacking
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[10,11],[12,13]])
vs=np.vstack((arr1,arr2))
print("vs:",vs)
hs=np.hstack((arr1,arr2))
print("hs:",hs)
#concatenation
con=np.concatenate((arr1,arr2))
print("con:",con)
app=np.append(arr1,arr2)
print("app:",app)

vs: [[ 1  2]
 [ 3  4]
 [10 11]
 [12 13]]
hs: [[ 1  2 10 11]
 [ 3  4 12 13]]
con: [[ 1  2]
 [ 3  4]
 [10 11]
 [12 13]]
app: [ 1  2  3  4 10 11 12 13]


In [57]:
#mathematical functions
arr1=np.array([10,30,45,60,90])
print("cos:",np.cos((np.pi/3)))
print("sin:",np.sin((np.pi/arr1)))
print("tan:",np.tan((np.pi/arr1)))
print("cosh:",np.cosh(arr1))
print("sqrt:",np.sqrt(arr1))
print("exp:",np.exp(arr1))
print("log:",np.log(arr1))

cos: 0.5000000000000001
sin: [0.30901699 0.10452846 0.06975647 0.05233596 0.0348995 ]
tan: [0.3249197  0.10510424 0.06992681 0.05240778 0.03492077]
cosh: [1.10132329e+04 5.34323729e+12 1.74671355e+19 5.71003695e+25
 6.10201647e+38]
sqrt: [3.16227766 5.47722558 6.70820393 7.74596669 9.48683298]
exp: [2.20264658e+04 1.06864746e+13 3.49342711e+19 1.14200739e+26
 1.22040329e+39]
log: [2.30258509 3.40119738 3.80666249 4.09434456 4.49980967]


In [63]:
#mathematical operations
arr1=np.array([10,20,30])
arr2=np.array([2,2,2])
print("addition:",np.add(arr1,arr2))
print("sub:",np.subtract(arr1,arr2))
print("multiply:",np.multiply(arr1,arr2))
print("divide:",np.divide(arr1,arr2))
print("power:",np.power(arr1,arr2))
print("remainder:",np.remainder(arr1,arr2))
print("reciprocal:",np.reciprocal(arr1,dtype=float))


addition: [12 22 32]
sub: [ 8 18 28]
multiply: [20 40 60]
divide: [ 5. 10. 15.]
power: [100 400 900]
remainder: [0 0 0]
reciprocal: [0.1        0.05       0.03333333]


In [69]:
#aggregates
print("mean:",np.mean(arr1))
print("var:",np.var(arr1))
print("std:",np.std(arr1))
print("sum:",np.sum(arr1))
print("prd:",np.prod(arr1))
print("all:",np.all(arr1))
print("any:",np.any(arr1))
print("cumsum:",np.cumsum(arr1))
print("min index:",np.argmin(arr1))
print("max index:",np.argmax(arr1))

mean: 20.0
var: 66.66666666666667
std: 8.16496580927726
sum: 60
prd: 6000
all: True
any: True
cumsum: [10 30 60]
min index: 0
max index: 2


In [76]:
#where
arr4=np.array([12,3,4])
g=np.where((arr4>10)&(arr4%2==0))
print(g)

(array([0], dtype=int64),)


In [89]:
#logical 
arr5=np.array([10,20,30,40])
print(np.logical_or(arr5>10,arr5<30))
print(np.logical_and(arr5>10,arr5<30))
print(np.logical_not(arr5>10))

[ True  True  True  True]
[False  True False False]
[ True False False False]


In [92]:
#sets
print("union:",np.union1d(arr4,arr5))
print("inters:",np.intersect1d(arr4,arr5))
print("diff:",np.setdiff1d(arr4,arr5))

union: [ 3  4 10 12 20 30 40]
inters: []
diff: [ 3  4 12]
