In [83]:
import numpy as np
first_d=np.array([1,2,3,4,5])
sec_d=np.array([[1,2,3],[4,5,6],[7,8,9]])
thr_d=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(first_d,sec_d,thr_d,sep="\n")
#get dimension
print("dim1:",first_d.ndim,"dim2:",sec_d.ndim,"dim3:",thr_d.ndim)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
dim1: 1 dim2: 2 dim3: 3


In [16]:
#reshape
first_d=first_d.reshape(5,1)
print(first_d,first_d.ndim,first_d.shape,sep="\n")

[[1]
 [2]
 [3]
 [4]
 [5]]
2
(5, 1)


In [19]:
#converting list or tuple into array
l=[1,2,3,4,5,6]
l_a=np.array(l)
print(l_a)
print(type(l_a))
p=(7,8,9,10)
t_a=np.array(p)
print(t_a,type(t_a),sep="\n")

[1 2 3 4 5 6]
<class 'numpy.ndarray'>
[ 7  8  9 10]
<class 'numpy.ndarray'>


In [20]:
#arange
p=np.arange(10)
print(p)

[0 1 2 3 4 5 6 7 8 9]


In [29]:
#linspace
lins=np.linspace(0,20,num=10,dtype="int")
lins

array([ 0,  2,  4,  6,  8, 11, 13, 15, 17, 20])

In [36]:
#logspace
logs=np.logspace(1,10,num=2,base=1)
logs

array([1., 1.])

In [41]:
#full array
full=np.full((5,1),2)
print(full)

[[2]
 [2]
 [2]
 [2]
 [2]]


In [43]:
#eye array
eye=np.eye(2,3)
print(eye)

[[1. 0. 0.]
 [0. 1. 0.]]


In [53]:
#random array
rand=np.random.rand(2,3)
print(rand)
rand2=np.random.randn(2,3)
print(rand2)
rand3=np.random.randint(2,size=(5,2))
print(rand3)

[[0.20284755 0.62534016 0.79992564]
 [0.19047714 0.95611378 0.14475905]]
[[ 1.8091139  -0.89823595 -0.96874225]
 [-1.25715098 -1.15853478 -0.25064178]]
[[0 1]
 [1 1]
 [1 0]
 [1 1]
 [0 0]]


In [68]:
#identity
id=np.identity(3)
print(id)
#diagnol
diag=np.diag(sec_d,k=2)
diag

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


array([3])

In [85]:
#indexing in multi-D
print(thr_d)
p=thr_d[0,1,1]
print(p)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
5


In [93]:
#1d array slicing
print(first_d[2:3])
#2d array slicing
print(sec_d[1:4])
#3d array slicing
print(thr_d[1:4])

[3]
[[4 5 6]
 [7 8 9]]
[[[1 2 3]
  [4 5 6]]]
